# Generated by Django 4.1.7 on 2023-04-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='agent_desc',
            field=models.TextField(max_length=200),
        ),
    ]
